### ISSUE TITLE
build from source (make build) failing

### ISSUE THREAD

**Issue by shinenelson** [terraform-providers/terraform-provider-linode#57] opened 2019-08-10 21:54 UTC
### Terraform Version
Terraform v0.12.7-dev

### Expected Behavior
What should have happened?
`make build` should have completed without any errors

### Actual Behavior
What actually happened?
```
==> Checking that code complies with gofmt requirements...
go install
verifying github.com/hashicorp/terraform@v0.12.0: checksum mismatch
	downloaded: h1:It2vmod2dBMB4+r+aUW2Afx0HlftyUwzNsNH3I2vrJ8=
	go.sum:     h1:B5lTDWSdEbbjxrTZQ8GdsDlH7FnDrIvF42GykbhQ6tA=
GNUmakefile:10: recipe for target 'build' failed
make: *** [build] Error 1
```

### Steps to Reproduce
* `git clone` the repository
* `make build`

### Important Factoids
I guess this is pretty much the exact same issue that was observed in https://github.com/terraform-providers/terraform-provider-digitalocean/issues/246#issuecomment-498311720. I believe (re-)generating go.sum ( rather than updating it ) should fix this issue.

**Comment by displague** [comment] 2019-08-12 13:33
I could not reproduce this @shinenelson 

What version of `go` are you using? There were `go mod` problems in versions before `1.11.4`.

**Comment by shinenelson** [comment] 2019-08-12 14:36
I'm running go version `go1.12.5 linux/amd64`.

I understand this wouldn't create a problem with your go mod cache. However, like andrewsomething mentioned in the https://github.com/terraform-providers/terraform-provider-digitalocean/issues/246#issuecomment-498311720 linked in my issue description, can you try removing `go.mod` and re-generating the file? 

Do you see a diff as mentioned in the description?
```
- h1:B5lTDWSdEbbjxrTZQ8GdsDlH7FnDrIvF42GykbhQ6tA=
+ h1:It2vmod2dBMB4+r+aUW2Afx0HlftyUwzNsNH3I2vrJ8=
```

**Comment by displague** [comment] 2019-08-12 18:25
I see. That does create a considerable diff.

/cc @ellisbenjamin @phillc

**Comment by phillc** [comment] 2019-09-18 15:34
#58 merged.

Thank you!

**Closed by phillc** 2019-09-18 15:34 UTC
